### ISSUE TITLE
Sort of dependency hell.

### ISSUE THREAD

**Issue by quark-tekliner** [marcelklehr/warp#3]
Warp should be dependent of gulf-contenteditable 1.0 to prevent serialization issue.
Gulp-contenteditable should dependent of dom-ot 2 to be abble to correct serialize dom element.

I didn't fixed it in pull request because i don't know does newer version dom-ot in gulp-contenteditable break anything else.

**Comment by marcelklehr** [comment]
Wow, good job figuring that out :)
fixed it just now, thank you!
